HTTP/1.1 200 OK
Content-Type: application/json

{
  "moreOrderResultsAvailable": false,
  "orderResults": [
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "CANCELLED",
      "orderStatusDateTime": "2018-11-25T13:20:03.157+01:00",
      "errorCode": "epcuzkadfobuuzoo",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "id": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "type": "AUTHORIZE",
          "status": "CANCELLED",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    },
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "CANCELLED",
      "orderStatusDateTime": "2018-11-25T13:20:03.157+01:00",
      "errorCode": "vihreotufop",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "id": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "type": "AUTHORIZE",
          "status": "SUCCESS",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    },
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "CANCELLED",
      "orderStatusDateTime": "2018-11-25T13:20:03.157+01:00",
      "errorCode": "faufa",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "id": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "type": "AUTHORIZE",
          "status": "CANCELLED",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    }
  ],
  "signature": "dc00219d04c8e9910c0b08df7b1db2119ef77181a9929ed4d3995d655aa5a295b66412f131ea173affa1ae71fab7cd7314f4c7f234d56e381d851091b630dc4b"
}
