HTTP/1.1 200 OK
Content-Type: application/json

{
  "moreOrderResultsAvailable": true,
  "orderResults": [
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "COMPLETED",
      "orderStatusDateTime": "2018-11-25T12:20:03.157+00:00",
      "errorCode": "fakekmirima",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "transactionId": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "transactionType": "AUTHORIZE",
          "transactionStatus": "SUCCESS",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startDateTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    },
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "COMPLETED",
      "orderStatusDateTime": "2018-11-25T12:20:03.157+00:00",
      "errorCode": "gupohaa",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "transactionId": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "transactionType": "AUTHORIZE",
          "transactionStatus": "SUCCESS",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startDateTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    },
    {
      "merchantOrderId": "order123",
      "omnikassaOrderId": "1d0a95f4-2589-439b-9562-c50aa19f9caf",
      "poiId": "2004",
      "orderStatus": "COMPLETED",
      "orderStatusDateTime": "2018-11-25T12:20:03.157+00:00",
      "errorCode": "voldeholu",
      "paidAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "totalAmount": {
        "amount": 10997,
        "currency": "EUR"
      },
      "transactions": [
        {
          "transactionId": "22b36073-57a3-4c3d-9585-87f2e55275a5",
          "paymentBrand": "IDEAL",
          "transactionType": "AUTHORIZE",
          "transactionStatus": "SUCCESS",
          "amount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "confirmedAmount": {
            "amount": 10997,
            "currency": "EUR"
          },
          "startDateTime": "2018-03-20T09:12:28Z",
          "lastUpdateTime": "2018-03-20T09:12:28Z"
        }
      ]
    }
  ],
  "signature": "132645b9059bb17201f5317d41371649c028ac7a7536ee70e895ddb57ff346d31f0d640b19b101514d4ce31eb64597f1da157af7a5da69290f46ad265c806d42"
}
